language: node_js
addons:
  apt:
    sources:
      - google-chrome
node_js:
  - "6"
services:
  - postgresql: "9.6"
before_script:
  - psql -c "create database doc_mgt_sys_test;" -U postgres
  - psql -c "CREATE USER mercymuchai;" -U postgres
  - sleep 3
after_script:
  - npm run coverage
env:
  - SECRET_TOKEN_KEY=nottheactualthing NODE_ENV=test
